name: build and cache random stuff
on:
  workflow_dispatch:
  push:
jobs:
  build:
    strategy:
      matrix:
        package:
          # - .#attic-client
          # - .#attic-server
          # - .#conduwuit
          - "github:cything/nixpkgs/9a35d495d2f49eee003b57265228844bb48c933e#nixosTests.garage.with-3node-replication1_x"
          - ".#nixosConfigurations.ytnix.config.system.build.images.iso"
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: cything
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - uses: actions/checkout@v4
      - run: nix build '${{ matrix.package }}' --show-trace -L
