name: build and cache random stuff

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        package:
          - github:cything/attic/e91261dc9a22d267700ab9095155f5581ac3b06c#attic
          - github:cything/attic/e91261dc9a22d267700ab9095155f5581ac3b06c#attic-server
          - github:cything/attic/e91261dc9a22d267700ab9095155f5581ac3b06c#attic-client

    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: cything
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - run: nix build '${{ matrix.package }}'
