name: build and cache random stuff
on:
  workflow_dispatch:
  push:
jobs:
  build-packages:
    strategy:
      matrix:
        package:
          - github:cything/nixpkgs/fd06e41125350bc3db5628df49d3b84e4652a59d#lact
        os:
          - ubuntu-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - run: nix build -L '${{ matrix.package }}'

  build-machines:
    strategy:
      matrix:
        machine:
          - chunk
          - ytnix
          - titan
        os:
          - ubuntu-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: /nix
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: nix build -L --accept-flake-config .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel

  build-homes:
    strategy:
      matrix:
        home:
          - yt@ytnix
          - yt@chunk
        os:
          - ubuntu-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: /nix
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: nix build -L --accept-flake-config .#homeConfigurations."${{ matrix.home }}".activationPackage
