name: build and cache random stuff

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        package:
          - .#attic-client
          - .#attic-server

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: cything
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - run: nix build '${{ matrix.package }}'
