name: build and cache random stuff
on:
  workflow_dispatch:
  push:
jobs:
  build:
    strategy:
      matrix:
        package:
          - .#attic-client
          - .#attic-server
          - .#conduwuit
          - "github:cything/nixpkgs/97f27249297bf5fbc563014ae9d4884dee27f1e0#nixosTests.garage.with-3node-replication1_x"
          - ".#nixosConfigurations.livecd.config.system.build.isoImage"
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - uses: actions/checkout@v4
      - run: nix build '${{ matrix.package }}'
      - name: Compress Build Craft
        run: |
          tar cvf "./$(date -I).tar" ./result/*
      - uses: actions/upload-artifact@v4
        with:
          path: ./*.tar
          overwrite: true
          retention-days: 7days
