name: build and cache random stuff

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: cything
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - run: nix build github:cything/attic/4938bf3584258e74d6f2036198eef81d7cdb4c85#attic
      - run: nix build github:cything/attic/4938bf3584258e74d6f2036198eef81d7cdb4c85#attic-server
      - run: nix build github:cything/attic/4938bf3584258e74d6f2036198eef81d7cdb4c85#attic-client
