name: "nix build and flake check"
on:
  pull_request:
  push:
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.github_token }}
    - run: nix flake check

  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.github_token }}
    - name: install nixfmt
      run: nix-env -f <nixpkgs> -iAP nixfmt-rfc-style
    - name: check that nix files are formatted correctly
      run : nixfmt --check
