name: "nix flake and fmt check"
on:
  pull_request:
  push:
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.github_token }}
      - run: nix flake check
