name: "update lazy plugins"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
permissions:
  pull-requests: write
  contents: write
jobs:
  update-lazy-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v30
      - name: Update vim plugins
        run: |
          export XDG_CONFIG_HOME=$PWD/home
          nix run nixpkgs#neovim -- --headless "+Lazy! update" +qa
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: update lazy plugins
          commit-message: update neovim plugins
