name: mirror to gitlab
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: mirror
        uses: SvanBoxel/gitlab-mirror-and-ci-action@5c211f993d35256d96b772d995972f434b94e11a
        with:
          args: "https://git.cything.io/cy/infra"
        env:
          FOLLOW_TAGS: "true"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "git.cything.io"
          GITLAB_USERNAME: "cy"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
